### PR TITLE
Add FAQ section

### PR DESCRIPTION
**Pull request by Limfjorden**

### CODE REVIEW

**Comment by hk21702** [comment]
Did you actually make a PR/push to the wiki repo? The commit reference change for the submodule points to something that doesn't seem to exist.

**Comment by Limfjorden** [comment]
I don't know how to PR the wiki repo, and it seems to have deleted my commit locally. I'll close this PR then.

**Comment by Limfjorden** [comment]
Closed.

**Comment by hk21702** [comment]
There are prob some workflow improvements that can be made to the wiki since it doesn't seem like GitHub supports pull requests for the wiki. 

For now, do something like this if you'd like to contribute. https://gist.github.com/larrybotha/10650410

Make a fork of the wiki itself, and then when ready, provide us with the direct link to that fork.

**Pull request closed without merging**
