### PR TITLE
update some constants to support DLC4 Anomaly

### PR DESCRIPTION
**Pull request by lisanhu**
Hi! I just updated some constants to support the newly out DLC Anomaly. Hope I'm doing it correctly.

I've edited 3 places of constants in `constants.py` `metadata.py` and `dependencies.py`.

Currently I'm running it with no problem.
image

Please stress test it and merge it when ready.

### CODE REVIEW

**Comment by lisanhu** [comment]
Just want to add that this PR is related to Issue https://github.com/RimSort/RimSort/issues/283#issue-2238790508

**Comment by oceancabbage** [comment]
Reviewing now

**Comment by oceancabbage** [comment]
Awesome, LGTM :) Thanks for making this change

**Review by oceancabbage — APPROVED** [review]

**Review by twstagg — APPROVED** [review]
💪

**Pull request merged**
