### PR TITLE
Catch non-empty directory error when deleting mod

### PR DESCRIPTION
**Pull request by Madrigalist**
Fix for #438

### CODE REVIEW

**Review by hk21702 — CHANGES_REQUESTED** [review]
Thanks for the PR.

Can you make it such that it catches all OSErrors? Any OS error shouldn't be a fatal error that causes RimSort to crash. Also, utilize logger.warning instead of debug and also use a show_warning dialogue to show a visible dialogue on catch. The user message should include e.winerror if the os is windows, e.errno otherwise, and also show e.strerror and e.filename.

**Comment by Madrigalist** [comment]
> Can you make it such that it catches all OSErrors? Any OS error shouldn't be a fatal error that causes RimSort to crash.

See changes. Is catching all OSErrors this way a good idea? I feel it should log them at least

**Comment by Madrigalist** [comment]
@hk21702 Have a look at the latest commit

**Review by oceancabbage — APPROVED** [review]

**Comment by LionelColaso** [comment]
> @hk21702 Have a look at the latest commit

Go ahead and Merge

**Pull request merged**
