### PR TITLE
Add an "Update all" button in the mod updater panel

### PR DESCRIPTION
**Pull request by lisanhu**
I always feel I need to select all and update selected mods. Then I realized maybe we need an "update all" button!

### CODE REVIEW

**Comment by lisanhu** [comment]
Ah, sorry, I just read the contributing guide and realized I should open an issue before this pull request.

**Review by LionelColaso — APPROVED** [review]
Personally i never thought of it but it makes sense
 like the changes i dont know how others feel about it

**Review by twstagg — APPROVED** [review]

**Comment by twstagg** [comment]
Sweet!

**Review by LionelColaso — APPROVED** [review]
``

**Pull request merged**
