### PR TITLE
New missing mods panel

### PR DESCRIPTION
**Pull request by twstagg**

### CODE REVIEW

**Comment by twstagg** [comment]
@cylian914 @loveboylion Please review

**Comment by loveboylion** [comment]
1) when Clicked `Download with SteamCMD`  opens `Download window`  but `Missing Mods Window` does not `Close the window` 

2) When Clicked `Do nothing and exit` It `Closes the window` and `Works as intended`

3) When Clicked `Download with SteamClient` Does Nothing when `No SteamClient` Found `Needs to be Checked with SteamClient`

image

**Comment by loveboylion** [comment]
Is this a Good Fix 
https://github.com/RimSort/RimSort/commit/f4a5d5eafc2c0a2b8f11c8a6b7eae9c1d767f7e4

**Review by cylian914 — APPROVED** [review]
This look good  but it need to have some qss change, you can push i will add them to the style branch

**Comment by twstagg** [comment]
@cylian914 pls add to style branch

**Pull request merged**
