### PR TITLE
Wiki previews

### PR DESCRIPTION
**Pull request by Chunnyluny**
Previews for Windows and Mac users are added in docs/wiki/users like we have discussed in the discord chat also see comment #184

### CODE REVIEW

**Comment by jefferyharrell** [comment]
Try using this Mac screenshot instead:

image

**Comment by Ant-V** [comment]
How about we just crop the window management bar, everything else is the exact same

**Review by twstagg — CHANGES_REQUESTED** [review]
Please add the Linux preview image as well (from the README)

**Review by twstagg — APPROVED** [review]
Thanks!

**Comment by twstagg** [comment]
Please update the wiki page with the changes made in this PR

**Pull request merged**
